name: peakScout

on:
  push:
    branches:
      - main 

jobs:
  compare-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.12'  

      - name: Install dependencies
        run: pip install polars numpy

      - name: Remove previous tests
        working-directory: test
        run: rm -rf results 

      - name: Test MACS2
        working-directory: test
        run: bash test_MACS2.sh

      - name: Test SEACR
        run: bash test_SEACR.sh