name: peakScout

on:
  push:
    branches:
      - main 

jobs:
  peakScout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.12'  

      - name: Install dependencies
        run: pip install polars numpy pandas openpyxl pyarrow

      - name: Create executable
        working-directory: src
        run: chmod +x peakScout

      - name: Add script directory to PATH
        run: echo "${{ github.workspace }}/src" >> $GITHUB_PATH

      - name: Remove previous tests
        working-directory: test
        run: bash remove_previous.sh

      - name: Test decomposition
        run: bash test/test_decomp.sh

      - name: Test MACS2 peak2gene
        run: bash test/test_MACS2.sh

      - name: Test SEACR peak2gene
        run: bash test/test_SEACR.sh